### ISSUE TITLE
ansible_port is not taken into account

### ISSUE THREAD

**Issue by rasjani** [yioda/ansible-inventory-to-ssh-config#3]
* Inventory defines hosts by just their "name" 
* each host has separate host_vars file that defines both IP and PORT (ansible_port)  for ssh access

Expected:

generated ssh config file would also have the port defined 

Only a list of hosts with `HostName $ip.h.e.re` are added

**Comment by yioda** [comment]
Hi @rasjani , thanks for your suggestion and provide a great PR!
Sorry that I didn't have much time to review. 
Here's new release [v1.0.1](https://pypi.org/project/ansible-inventory-to-ssh-config/) with following new features you could try~

- Default without backup.
- Support `--override` option, this would remove those host undefined in playbook.
- Support parsing `ansibl_ssh_port`/`ansible_port` and `ansible_ssh_user`/`ansible_user` as host's SSH connection information.
- Adjust dry run print result to ssh config format exactly.
- Dependencies version limitation.
  - ansible==2.10.7
  - sshconf==0.2.5
